apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sqldb
  labels:
    app: techchallenge
    tier: backend
spec:
  selector:
    matchLabels:
      app: techchallenge
      tier: backend
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: techchallenge
        tier: backend
    spec:
      containers:
        - image: diogomuniz/techchallenge-mysql:v2
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: secret
            - name: MYSQL_DATABASE
              value: dbpostech
            - name: MYSQL_PASSWORD
              value: secret
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306
